name = "Simulacoes"
uuid = "4efb01ef-14a3-4e22-a218-cb2c27a6f75a"
authors = ["Leonardo J. Duarte <leo.j.duarte@hotmail.com.br> and contributors"]
version = "0.1.5"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Parameters = "0.12.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
